#!/usr/bin/env python

import rospy
import sys
from mavros_msgs.srv import CommandLong, CommandLongRequest


def main(argv):
    for arg in argv:
        try:
            uuv_namespace = "uuv{:02d}".format(int(arg))
        except ValueError as e:
            print(e)
            print("Could not arm vehicle with arg: {}".format(arg))
            continue

        try:
            proxy = rospy.ServiceProxy(
                "/{}/mavros/cmd/command".format(uuv_namespace), CommandLong)
            req = CommandLongRequest(broadcast=False,
                                     command=400,
                                     confirmation=0,
                                     param1=1,
                                     param2=21196,
                                     param3=0,
                                     param4=0,
                                     param5=0,
                                     param6=0,
                                     param7=0)

            proxy(req)
        except rospy.ServiceException as e:
            print("Arming failed: {}".format(e))
        else:
            print("Armed {}".format(uuv_namespace))

    print("Finished!")


if __name__ == "__main__":
    main(rospy.myargv(sys.argv))
